apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-ms-deployment
spec:
  selector:
    matchLabels:
      app: mongodb-ms
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-ms
    spec:
      containers:
        - name: mongodb-ms
          image: mongodb-ms
          ports:
            - containerPort: 8080
              name: api-port
          env:
            - name: mongodb
              value: mongodb://root:rootpassword@mongo-service:27017/

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: api-port
  selector:
    app: mongodb-ms
  type: NodePort