apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ms-deployment
spec:
  selector:
    matchLabels:
      app: data_ms
  replicas: 1
  template:
    metadata:
      labels:
        app: data_ms
    spec:
      containers:
        - name: data-ms
          image: hello-ms
          ports:
            - containerPort: 8080
              name: api-port
          env:
            - name: api.host
              value: http://numbersapi.com
---
apiVersion: v1
kind: Service
metadata:
  name: hello-ms-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: api-port
  selector:
    app: data_ms
  type: NodePort