apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ms-deployment
spec:
  selector:
    matchLabels:
      app: data_ms
  replicas: 1
  template:
    metadata:
      labels:
        app: data_ms
    spec:
      containers:
        - name: data-ms
          image: data-ms
          ports:
            - containerPort: 8080
              name: api-port
          env:
            - name: numbers-api.host
              value: http://numbersapi.com
            - name: goodbye-api.host
              value: goodbye-service
            - name: mongodb-service.host
              value: mongodb-service
---
apiVersion: v1
kind: Service
metadata:
  name: data-ms-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: api-port
  selector:
    app: data_ms
  type: NodePort