apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodbye-ms-deployment
spec:
  selector:
    matchLabels:
      app: goodbye-ms
  replicas: 1
  template:
    metadata:
      labels:
        app: goodbye-ms
    spec:
      containers:
        - name: goodbye-ms
          image: goodbye-ms
          ports:
            - containerPort: 8080
              name: api-port
---
apiVersion: v1
kind: Service
metadata:
  name: goodbye-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: api-port
  selector:
    app: goodbye-ms
  type: NodePort